{{
    config(
        materialized='incremental',
        incremental_strategy='merge',
        unique_key=['chave_acesso', 'n_item'],
        on_schema_change='fail',
        indexes=[{'columns': ['lote_id']}, {'columns': ['ncm']}],
    )
}}

-- Itens (det) com todos os tributos: 1 linha por chave + nItem.
-- 'n:ICMS/*/...' resolve o grupo variável (ICMS00, ICMS20, ICMS40...); idem PIS/COFINS/IPI.
with xml_vigente as (
    select * from {{ ref('int_nfe__xml_vigente') }}
)

select
    x.chave_acesso,
    d.n_item,
    x.lote_id,
    d.cprod,
    d.xprod,
    d.ncm,
    d.cfop,
    d.c_benef,
    d.ucom,
    d.qcom::numeric(15,4)               as qcom,
    d.vuncom::numeric(21,10)            as vuncom,
    d.vprod::numeric(15,2)              as vprod,
    d.cst_icms,
    d.p_red_bc_icms::numeric(7,4)       as p_red_bc_icms,
    d.vbc_icms::numeric(15,2)           as vbc_icms,
    d.p_icms::numeric(7,4)              as p_icms,
    d.v_icms::numeric(15,2)             as v_icms,
    d.v_icms_deson::numeric(15,2)       as v_icms_deson,
    coalesce(d.cst_ipi_trib, d.cst_ipi_nt) as cst_ipi,
    d.v_ipi::numeric(15,2)              as v_ipi,
    d.cst_pis,
    d.v_pis::numeric(15,2)              as v_pis,
    d.cst_cofins,
    d.v_cofins::numeric(15,2)           as v_cofins,
    d.cst_ibscbs,
    d.cclasstrib,
    d.vbc_ibscbs::numeric(15,2)         as vbc_ibscbs,
    d.p_ibs_uf::numeric(7,4)            as p_ibs_uf,
    d.p_red_aliq::numeric(7,4)          as p_red_aliq,
    d.p_aliqefet_ibs_uf::numeric(7,4)   as p_aliqefet_ibs_uf,
    d.p_dif::numeric(7,4)               as p_dif,
    d.v_dif_ibs_uf::numeric(15,2)       as v_dif_ibs_uf,
    d.v_devtrib_ibs_uf::numeric(15,2)   as v_devtrib_ibs_uf,
    d.v_ibs_uf::numeric(15,2)           as v_ibs_uf,
    d.p_ibs_mun::numeric(7,4)           as p_ibs_mun,
    d.v_dif_ibs_mun::numeric(15,2)      as v_dif_ibs_mun,
    d.v_devtrib_ibs_mun::numeric(15,2)  as v_devtrib_ibs_mun,
    d.v_ibs_mun::numeric(15,2)          as v_ibs_mun,
    d.v_ibs::numeric(15,2)              as v_ibs,
    d.p_cbs::numeric(7,4)               as p_cbs,
    d.p_aliqefet_cbs::numeric(7,4)      as p_aliqefet_cbs,
    d.v_dif_cbs::numeric(15,2)          as v_dif_cbs,
    d.v_devtrib_cbs::numeric(15,2)      as v_devtrib_cbs,
    d.v_cbs::numeric(15,2)              as v_cbs,
    d.cst_is,
    d.cclasstrib_is,
    d.v_bc_is::numeric(15,2)            as v_bc_is,
    d.p_is::numeric(7,4)                as p_is,
    d.v_is::numeric(15,2)               as v_is,
    d.v_item::numeric(15,2)             as v_item,
    x.carregado_em,
    now()                               as dbt_processado_em
from xml_vigente as x
cross join xmltable(
    {{ nfe_ns() }},
    '/n:nfeProc/n:NFe/n:infNFe/n:det | /n:NFe/n:infNFe/n:det'
    passing x.conteudo
    columns
        n_item              int     path '@nItem',
        cprod               text    path 'n:prod/n:cProd',
        xprod               text    path 'n:prod/n:xProd',
        ncm                 text    path 'n:prod/n:NCM',
        cfop                text    path 'n:prod/n:CFOP',
        c_benef             text    path 'n:prod/n:cBenef',
        ucom                text    path 'n:prod/n:uCom',
        qcom                numeric path 'n:prod/n:qCom',
        vuncom              numeric path 'n:prod/n:vUnCom',
        vprod               numeric path 'n:prod/n:vProd',
        cst_icms            text    path 'n:imposto/n:ICMS/*/n:CST',
        p_red_bc_icms       numeric path 'n:imposto/n:ICMS/*/n:pRedBC',
        vbc_icms            numeric path 'n:imposto/n:ICMS/*/n:vBC',
        p_icms              numeric path 'n:imposto/n:ICMS/*/n:pICMS',
        v_icms              numeric path 'n:imposto/n:ICMS/*/n:vICMS',
        v_icms_deson        numeric path 'n:imposto/n:ICMS/*/n:vICMSDeson',
        cst_ipi_trib        text    path 'n:imposto/n:IPI/n:IPITrib/n:CST',
        cst_ipi_nt          text    path 'n:imposto/n:IPI/n:IPINT/n:CST',
        v_ipi               numeric path 'n:imposto/n:IPI/n:IPITrib/n:vIPI',
        cst_pis             text    path 'n:imposto/n:PIS/*/n:CST',
        v_pis               numeric path 'n:imposto/n:PIS/*/n:vPIS',
        cst_cofins          text    path 'n:imposto/n:COFINS/*/n:CST',
        v_cofins            numeric path 'n:imposto/n:COFINS/*/n:vCOFINS',
        cst_ibscbs          text    path 'n:imposto/n:IBSCBS/n:CST',
        cclasstrib          text    path 'n:imposto/n:IBSCBS/n:cClassTrib',
        vbc_ibscbs          numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:vBC',
        p_ibs_uf            numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:pIBSUF',
        p_red_aliq          numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:gRed/n:pRedAliq',
        p_aliqefet_ibs_uf   numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:gRed/n:pAliqEfet',
        p_dif               numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:gDif/n:pDif',
        v_dif_ibs_uf        numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:gDif/n:vDif',
        v_devtrib_ibs_uf    numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:gDevTrib/n:vDevTrib',
        v_ibs_uf            numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSUF/n:vIBSUF',
        p_ibs_mun           numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSMun/n:pIBSMun',
        v_dif_ibs_mun       numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSMun/n:gDif/n:vDif',
        v_devtrib_ibs_mun   numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSMun/n:gDevTrib/n:vDevTrib',
        v_ibs_mun           numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gIBSMun/n:vIBSMun',
        v_ibs               numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:vIBS',
        p_cbs               numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gCBS/n:pCBS',
        p_aliqefet_cbs      numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gCBS/n:gRed/n:pAliqEfet',
        v_dif_cbs           numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gCBS/n:gDif/n:vDif',
        v_devtrib_cbs       numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gCBS/n:gDevTrib/n:vDevTrib',
        v_cbs               numeric path 'n:imposto/n:IBSCBS/n:gIBSCBS/n:gCBS/n:vCBS',
        cst_is              text    path 'n:imposto/n:IS/n:CSTIS',
        cclasstrib_is       text    path 'n:imposto/n:IS/n:cClassTribIS',
        v_bc_is             numeric path 'n:imposto/n:IS/n:vBCIS',
        p_is                numeric path 'n:imposto/n:IS/n:pIS',
        v_is                numeric path 'n:imposto/n:IS/n:vIS',
        v_item              numeric path 'n:vItem'
) as d
