{{
    config(
        materialized='incremental',
        incremental_strategy='merge',
        unique_key='chave_acesso',
        on_schema_change='fail',
        indexes=[
            {'columns': ['lote_id']},
            {'columns': ['dt_emissao']},
            {'columns': ['emit_cnpj']},
        ],
    )
}}

-- Cabeçalho da NF-e (ide, emit, dest, totais, protocolo): 1 linha por chave de acesso.
-- Parse 100% SQL com XMLTABLE. A raiz pode ser <nfeProc> (com protocolo) ou <NFe>.
with xml_vigente as (
    select * from {{ ref('int_nfe__xml_vigente') }}
)

select
    x.chave_acesso,
    x.lote_id,
    x.arquivo,
    x.hash_conteudo,
    t.versao_layout,
    t.cod_uf,
    t.modelo,
    t.serie,
    t.nnf,
    t.dh_emissao,
    (t.dh_emissao at time zone 'America/Sao_Paulo')::date  as dt_emissao,
    t.nat_op,
    t.tp_nf,
    t.fin_nfe,
    t.id_dest,
    t.ind_final,
    t.ind_pres,
    t.tp_amb,
    t.chave_referenciada,
    t.emit_cnpj,
    t.emit_nome,
    t.emit_ie,
    t.emit_crt,
    t.emit_uf,
    t.emit_cod_municipio,
    t.emit_municipio,
    t.emit_logradouro,
    t.emit_bairro,
    t.emit_cep,
    case when t.dest_cnpj is not null then 'CNPJ' else 'CPF' end   as dest_tipo_doc,
    coalesce(t.dest_cnpj, t.dest_cpf)                              as dest_doc,
    t.dest_nome,
    t.dest_ie,
    t.dest_ind_ie,
    t.dest_uf,
    t.dest_cod_municipio,
    t.dest_municipio,
    t.dest_logradouro,
    t.dest_bairro,
    t.dest_cep,
    t.v_prod::numeric(15,2)            as v_prod,
    t.v_bc_icms::numeric(15,2)         as v_bc_icms,
    t.v_icms::numeric(15,2)            as v_icms,
    t.v_icms_deson::numeric(15,2)      as v_icms_deson,
    t.v_ipi::numeric(15,2)             as v_ipi,
    t.v_pis::numeric(15,2)             as v_pis,
    t.v_cofins::numeric(15,2)          as v_cofins,
    t.v_nf::numeric(15,2)              as v_nf,
    t.v_bc_ibscbs::numeric(15,2)       as v_bc_ibscbs,
    t.v_ibs_uf::numeric(15,2)          as v_ibs_uf,
    t.v_ibs_mun::numeric(15,2)         as v_ibs_mun,
    t.v_ibs::numeric(15,2)             as v_ibs,
    t.v_cbs::numeric(15,2)             as v_cbs,
    t.v_dif_ibs_uf::numeric(15,2)      as v_dif_ibs_uf,
    t.v_dif_ibs_mun::numeric(15,2)     as v_dif_ibs_mun,
    t.v_dif_cbs::numeric(15,2)         as v_dif_cbs,
    t.v_devtrib_ibs_uf::numeric(15,2)  as v_devtrib_ibs_uf,
    t.v_devtrib_ibs_mun::numeric(15,2) as v_devtrib_ibs_mun,
    t.v_devtrib_cbs::numeric(15,2)     as v_devtrib_cbs,
    t.v_credpres_ibs::numeric(15,2)    as v_credpres_ibs,
    t.v_credpres_cbs::numeric(15,2)    as v_credpres_cbs,
    t.v_is::numeric(15,2)              as v_is,
    t.v_nf_tot::numeric(15,2)          as v_nf_tot,
    t.qtd_itens::int                   as qtd_itens,
    t.n_protocolo,
    t.dh_autorizacao,
    t.c_stat,
    x.carregado_em,
    now()                              as dbt_processado_em
from xml_vigente as x
cross join xmltable(
    {{ nfe_ns() }},
    '/n:nfeProc/n:NFe/n:infNFe | /n:NFe/n:infNFe'
    passing x.conteudo
    columns
        versao_layout       text        path '@versao',
        cod_uf              text        path 'n:ide/n:cUF',
        modelo              text        path 'n:ide/n:mod',
        serie               int         path 'n:ide/n:serie',
        nnf                 bigint      path 'n:ide/n:nNF',
        dh_emissao          timestamptz path 'n:ide/n:dhEmi',
        nat_op              text        path 'n:ide/n:natOp',
        tp_nf               text        path 'n:ide/n:tpNF',
        fin_nfe             text        path 'n:ide/n:finNFe',
        id_dest             text        path 'n:ide/n:idDest',
        ind_final           text        path 'n:ide/n:indFinal',
        ind_pres            text        path 'n:ide/n:indPres',
        tp_amb              text        path 'n:ide/n:tpAmb',
        chave_referenciada  text        path 'n:ide/n:NFref/n:refNFe',
        emit_cnpj           text        path 'n:emit/n:CNPJ',
        emit_nome           text        path 'n:emit/n:xNome',
        emit_ie             text        path 'n:emit/n:IE',
        emit_crt            text        path 'n:emit/n:CRT',
        emit_uf             text        path 'n:emit/n:enderEmit/n:UF',
        emit_cod_municipio  text        path 'n:emit/n:enderEmit/n:cMun',
        emit_municipio      text        path 'n:emit/n:enderEmit/n:xMun',
        emit_logradouro     text        path 'n:emit/n:enderEmit/n:xLgr',
        emit_bairro         text        path 'n:emit/n:enderEmit/n:xBairro',
        emit_cep            text        path 'n:emit/n:enderEmit/n:CEP',
        dest_cnpj           text        path 'n:dest/n:CNPJ',
        dest_cpf            text        path 'n:dest/n:CPF',
        dest_nome           text        path 'n:dest/n:xNome',
        dest_ie             text        path 'n:dest/n:IE',
        dest_ind_ie         text        path 'n:dest/n:indIEDest',
        dest_uf             text        path 'n:dest/n:enderDest/n:UF',
        dest_cod_municipio  text        path 'n:dest/n:enderDest/n:cMun',
        dest_municipio      text        path 'n:dest/n:enderDest/n:xMun',
        dest_logradouro     text        path 'n:dest/n:enderDest/n:xLgr',
        dest_bairro         text        path 'n:dest/n:enderDest/n:xBairro',
        dest_cep            text        path 'n:dest/n:enderDest/n:CEP',
        v_prod              numeric     path 'n:total/n:ICMSTot/n:vProd',
        v_bc_icms           numeric     path 'n:total/n:ICMSTot/n:vBC',
        v_icms              numeric     path 'n:total/n:ICMSTot/n:vICMS',
        v_icms_deson        numeric     path 'n:total/n:ICMSTot/n:vICMSDeson',
        v_ipi               numeric     path 'n:total/n:ICMSTot/n:vIPI',
        v_pis               numeric     path 'n:total/n:ICMSTot/n:vPIS',
        v_cofins            numeric     path 'n:total/n:ICMSTot/n:vCOFINS',
        v_nf                numeric     path 'n:total/n:ICMSTot/n:vNF',
        v_bc_ibscbs         numeric     path 'n:total/n:IBSCBSTot/n:vBCIBSCBS',
        v_ibs_uf            numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:gIBSUF/n:vIBSUF',
        v_ibs_mun           numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:gIBSMun/n:vIBSMun',
        v_ibs               numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:vIBS',
        v_cbs               numeric     path 'n:total/n:IBSCBSTot/n:gCBS/n:vCBS',
        v_dif_ibs_uf        numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:gIBSUF/n:vDif',
        v_dif_ibs_mun       numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:gIBSMun/n:vDif',
        v_dif_cbs           numeric     path 'n:total/n:IBSCBSTot/n:gCBS/n:vDif',
        v_devtrib_ibs_uf    numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:gIBSUF/n:vDevTrib',
        v_devtrib_ibs_mun   numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:gIBSMun/n:vDevTrib',
        v_devtrib_cbs       numeric     path 'n:total/n:IBSCBSTot/n:gCBS/n:vDevTrib',
        v_credpres_ibs      numeric     path 'n:total/n:IBSCBSTot/n:gIBS/n:vCredPres',
        v_credpres_cbs      numeric     path 'n:total/n:IBSCBSTot/n:gCBS/n:vCredPres',
        v_is                numeric     path 'n:total/n:ISTot/n:vIS',
        v_nf_tot            numeric     path 'n:total/n:vNFTot',
        qtd_itens           numeric     path 'count(n:det)',
        n_protocolo         text        path '../../n:protNFe/n:infProt/n:nProt',
        dh_autorizacao      timestamptz path '../../n:protNFe/n:infProt/n:dhRecbto',
        c_stat              text        path '../../n:protNFe/n:infProt/n:cStat'
) as t
